x-netbox-environment: &netbox-environment
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_WAIT_DEBUG: "1"
  DB_NAME: ${POSTGRES_DB}
  DB_USER: ${POSTGRES_USER}
  DB_PASSWORD: ${POSTGRES_PASSWORD}
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_SSL: "false"
  REDIS_CACHE_HOST: redis-cache
  REDIS_CACHE_PORT: "6379"
  REDIS_CACHE_DATABASE: "1"
  REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}
  REDIS_CACHE_SSL: "false"

services:
  netbox:
    image: docker.io/netboxcommunity/netbox:v4.7-5.1.1
    env_file:
      - stack.env
    environment: *netbox-environment
    networks:
      - netbox-internal
    user: "netbox:root"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    ports:
      - "${NETBOX_PORT}:8080"
    healthcheck:
      test: /opt/netbox/health.sh
      start_period: 90s
      timeout: 3s
      interval: 15s
      retries: 5
    volumes:
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw

  netbox-worker:
    image: docker.io/netboxcommunity/netbox:v4.7-5.1.1
    env_file:
      - stack.env
    environment: *netbox-environment
    networks:
      - netbox-internal
    user: "netbox:root"
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/venv/bin/python
      - /opt/netbox/netbox/manage.py
      - rqworker
    healthcheck:
      test: ps -aux | grep -v grep | grep -q rqworker || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 5
    volumes:
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw

  netbox-housekeeping:
    image: docker.io/netboxcommunity/netbox:v4.7-5.1.1
    env_file:
      - stack.env
    environment: *netbox-environment
    networks:
      - netbox-internal
    user: "netbox:root"
    depends_on:
      netbox:
        condition: service_healthy
    command:
      - /opt/netbox/housekeeping.sh
    volumes:
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw

  postgres:
    image: docker.io/postgres:18-alpine
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - netbox-internal
    healthcheck:
      test: pg_isready -q -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER
      start_period: 20s
      timeout: 30s
      interval: 10s
      retries: 5
    volumes:
      - netbox-postgres:/var/lib/postgresql

  redis:
    image: docker.io/valkey/valkey:9.1-alpine
    env_file:
      - stack.env
    networks:
      - netbox-internal
    command:
      - sh
      - -c
      - valkey-server --appendonly yes --requirepass $$REDIS_PASSWORD
    healthcheck: &valkey-healthcheck
      test: '[ $$(valkey-cli --pass "$$REDIS_PASSWORD" ping) = "PONG" ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    volumes:
      - netbox-redis-data:/data

  redis-cache:
    image: docker.io/valkey/valkey:9.1-alpine
    env_file:
      - stack.env
    networks:
      - netbox-internal
    command:
      - sh
      - -c
      - valkey-server --requirepass $$REDIS_CACHE_PASSWORD
    healthcheck:
      test: '[ $$(valkey-cli --pass "$$REDIS_CACHE_PASSWORD" ping) = "PONG" ]'
      start_period: 5s
      timeout: 3s
      interval: 1s
      retries: 5
    volumes:
      - netbox-redis-cache-data:/data

volumes:
  netbox-media-files:
  netbox-postgres:
  netbox-redis-cache-data:
  netbox-redis-data:
  netbox-reports-files:
  netbox-scripts-files:

networks:
  netbox-internal:
    name: ${NETBOX_NETWORK_NAME}
    driver: bridge
